---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  apt:
    name:
      - curl
      - ufw
      - htop
    state: present

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Allow SSH in ufw
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled
    policy: deny
    direction: incoming
