[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/automataops-key-new.pem
ansible_ssh_common_args="-o StrictHostKeyChecking=accept-new"
ansible_python_interpreter=/usr/bin/python3

[master]
master ansible_host=34.235.150.4 ansible_private_ip=10.0.1.147

[workers]
worker1 ansible_host=98.92.176.178 ansible_private_ip=10.0.1.126
worker2 ansible_host=50.16.21.73 ansible_private_ip=10.0.2.54

[cluster:children]
master
workers
