---
- name: Prepare nodes and install k3s
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - common

- name: Install k3s server
  hosts: master
  become: yes
  roles:
    - k3s-server

- name: Install k3s agents
  hosts: workers
  become: yes
  roles:
    - k3s-agent
