apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: taskapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: ghcr.io/ts-a-devops/taskapp-backend@sha256:7ebe1b93baef2c95098d6ce253879b4067ffbe39645a9c4fa5513aff202e4a70
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Waiting for Postgres...";
          until pg_isready -h postgres -U taskapp; do sleep 2; done;
          alembic upgrade head
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: taskapp-secret
              key: DATABASE_URL
